### ISSUE TITLE
Symlinks created in windows are not accessible

### ISSUE THREAD

**Issue by marcharding** [winnfsd/winnfsd#10]
When one creates a symlink in windows it is not accessible over nfs. The folder is shown but its not possible to cd into it.

e.g. create a symlink under windows with

```
mklink /D D:\path\to\nfs-mount\target-folder D:\source-folder
```

and try to access is in linux over the nfs share...

**Comment by achekulaev** [comment]
subscribe

**Comment by achekulaev** [comment]
Also junctions do not work at all.

**Comment by HnLn** [comment]
I reported the same issue on the vagrant plugin repo https://github.com/winnfsd/vagrant-winnfsd/issues/69

**Comment by manuelbieh** [comment]
Similar error here (Win 10 Pro). I created a symlink `mklink /D Foo "node_modules\foo`. When I `cd` into the the directory in a vagrant box and then try to `ls -l` all files, winnfsd crashes completely.

**Comment by marcharding** [comment]
Fixed with c2e7bfc65e855c5d4dbcdec13e4c4179c19cb05b.

**Comment by HnLn** [comment]
Still not working here, but vagrant said there were no updates for the plugin, so maybe I just need to wait a bit.

**Comment by marcharding** [comment]
see https://github.com/winnfsd/winnfsd/issues/11#issuecomment-228266348
