### ISSUE TITLE
Mounting from MacOS - PORTMAP NOTIMP

### ISSUE THREAD

**Issue by achekulaev** [winnfsd/winnfsd#28]
Does not mount at all. Never mounted for me actually. 
Winnfsd is running on Win 10 inside Virtual Box

<img width="1440" alt="winnfsd-win10-macos" src="https://cloud.githubusercontent.com/assets/402007/16861792/14ca4560-4a12-11e6-98e5-b5c6717893dd.png">

**Comment by marcharding** [comment]
Interesting setup :smile:

A few things to try first:

1. Disable the windows firewall
2. TCP is kind of broken, please try with UDP (or try the exe here https://github.com/winnfsd/winnfsd/issues/22#issuecomment-232504404)
3. Try the last two version as quite a lot has changes, while i added some tests i'm not sure i did not brake something. https://github.com/winnfsd/winnfsd/releases/download/1.0.1/winnfsd.exe and https://github.com/winnfsd/winnfsd/releases/download/2.1.0/WinNFSd.exe)

**Comment by marcharding** [comment]
Hey @achekulaev, any news here?

**Comment by achekulaev** [comment]
Hey @marcharding 

Sorry for the delay. The result is the same

![image](https://cloud.githubusercontent.com/assets/402007/17194888/9102e34c-5428-11e6-9890-f758ebac3fb9.png)

**Comment by marcharding** [comment]
Hm, can you capture the process with wireshark (i'm guessing you issue may be similar to https://github.com/winnfsd/vagrant-winnfsd/issues/12#issuecomment-77448323)?

**Comment by achekulaev** [comment]
Does it matter on which side to capture the process?

**Comment by marcharding** [comment]
You can capture from OSX, i just want to know if PMAPPROC_DUMP instead of PMAPPROC_GETPORT is send. I'll also look into this myself later (maybe i can reproduce it with boot2docker, like in the comment).

**Comment by marcharding** [comment]
I can reproduce this with boot2docker, no need for wireshark.

I'll try to fix this.

**Comment by marcharding** [comment]
Hey @achekulaev, please try  again with [this binary](https://github.com/winnfsd/winnfsd/files/389236/WinNFSd.zip). I'm positive that it'll work.

**Comment by marcharding** [comment]
This should be fixed with https://github.com/winnfsd/winnfsd/releases/tag/2.2.0. Please try again.

**Comment by achekulaev** [comment]
@marcharding thanks it works indeed!

**Comment by aselby** [comment]
![image](https://cloud.githubusercontent.com/assets/10297047/18819059/97533ee2-8356-11e6-8a1c-125e53f37e4b.png)

I'm still having the issue when connecting from kodi (kodi.tv)

**Comment by marcharding** [comment]
@aselby i just fixed kodi support in the last few days, will release a new version later today.

**Comment by marcharding** [comment]
Please test with this version [WinNFSd.zip](https://github.com/winnfsd/winnfsd/files/494140/WinNFSd.zip) and report back. I'll probably release this tomorrow (would be nice if you can report back by then).

I'm using it with kodi without problems.

**Comment by aselby** [comment]
As soon as the debate is over ... I will give it a try ... thanks

**Comment by aselby** [comment]
![image](https://cloud.githubusercontent.com/assets/10297047/18897298/f9779fc2-84f6-11e6-80b9-a824e4244086.png)
This is with the new version you sent, when I add a network source (on kodi) and either click on Network File System (NFS) or on a nfs:// share that browses to it this is what I get

**Comment by aselby** [comment]
![image](https://cloud.githubusercontent.com/assets/10297047/18897325/4e1ca4be-84f7-11e6-8678-f0203be6aa02.png)
when I click on the share that worked with the old version ... I now get this mounted in the OS

**Comment by marcharding** [comment]
/ as the share does not work, try it like this and it should work (just tested it with kodi):

`winnfsd.exe s:\movies /movies`

**Comment by marcharding** [comment]
With [WinNFSd.zip](https://github.com/winnfsd/winnfsd/files/498839/WinNFSd.zip) / works again as a share.

Final release coming later.

**Comment by aselby** [comment]
I will try it ... does the "discovery" work ?
